.TH "_djw_stream" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_djw_stream \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBunused\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file xdelta3-djw.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
