.TH "_djw_prefix" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_djw_prefix \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBscount\fP"
.br
.ti -1c
.RI "uint8_t * \fBsymbol\fP"
.br
.ti -1c
.RI "usize_t \fBmcount\fP"
.br
.ti -1c
.RI "uint8_t * \fBmtfsym\fP"
.br
.ti -1c
.RI "uint8_t * \fBrepcnt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file xdelta3-djw.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
