.TH "_fgk_block" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fgk_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBfgk_node\fP * \fBun_leader\fP"
.br
.ti -1c
.RI "   \fBfgk_block\fP * \fBun_freeptr\fP"
.br
.ti -1c
.RI "} \fBun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file xdelta3-fgk.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
