.TH "_fgk_stream" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fgk_stream \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBalphabet_size\fP"
.br
.ti -1c
.RI "usize_t \fBzero_freq_count\fP"
.br
.ti -1c
.RI "usize_t \fBzero_freq_exp\fP"
.br
.ti -1c
.RI "usize_t \fBzero_freq_rem\fP"
.br
.ti -1c
.RI "usize_t \fBcoded_depth\fP"
.br
.ti -1c
.RI "usize_t \fBtotal_nodes\fP"
.br
.ti -1c
.RI "usize_t \fBtotal_blocks\fP"
.br
.ti -1c
.RI "fgk_bit * \fBcoded_bits\fP"
.br
.ti -1c
.RI "\fBfgk_block\fP * \fBblock_array\fP"
.br
.ti -1c
.RI "\fBfgk_block\fP * \fBfree_block\fP"
.br
.ti -1c
.RI "\fBfgk_node\fP * \fBdecode_ptr\fP"
.br
.ti -1c
.RI "\fBfgk_node\fP * \fBremaining_zeros\fP"
.br
.ti -1c
.RI "\fBfgk_node\fP * \fBalphabet\fP"
.br
.ti -1c
.RI "\fBfgk_node\fP * \fBroot_node\fP"
.br
.ti -1c
.RI "\fBfgk_node\fP * \fBfree_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file xdelta3-fgk.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
