.TH "_main_blklru" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_main_blklru \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBblk\fP"
.br
.ti -1c
.RI "xoff_t \fBblkno\fP"
.br
.ti -1c
.RI "usize_t \fBsize\fP"
.br
.ti -1c
.RI "\fBmain_blklru_list\fP \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file xdelta3-blkcache.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
