.TH "_main_extcomp" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_main_extcomp \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBrecomp_cmdname\fP"
.br
.ti -1c
.RI "const char * \fBrecomp_options\fP"
.br
.ti -1c
.RI "const char * \fBdecomp_cmdname\fP"
.br
.ti -1c
.RI "const char * \fBdecomp_options\fP"
.br
.ti -1c
.RI "const char * \fBident\fP"
.br
.ti -1c
.RI "const char * \fBmagic\fP"
.br
.ti -1c
.RI "usize_t \fBmagic_size\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 198 of file xdelta3-main.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
