.TH "_main_file" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_main_file \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBfilename_copy\fP"
.br
.ti -1c
.RI "const char * \fBrealname\fP"
.br
.ti -1c
.RI "const \fBmain_extcomp\fP * \fBcompressor\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "xoff_t \fBnread\fP"
.br
.ti -1c
.RI "xoff_t \fBnwrite\fP"
.br
.ti -1c
.RI "uint8_t * \fBsnprintf_buf\fP"
.br
.ti -1c
.RI "int \fBsize_known\fP"
.br
.ti -1c
.RI "xoff_t \fBsource_position\fP"
.br
.ti -1c
.RI "int \fBseek_failed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file xdelta3-internal.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
