.TH "_main_merge_list" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_main_merge_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmain_merge_list\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBmain_merge_list\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 214 of file xdelta3-main.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
