.TH "_main_merge" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_main_merge \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "\fBmain_merge_list\fP \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file xdelta3-main.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
