.TH "_xd3_wininfo" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_wininfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "xoff_t \fBoffset\fP"
.br
.ti -1c
.RI "usize_t \fBlength\fP"
.br
.ti -1c
.RI "uint32_t \fBadler32\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 647 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
