.TH "_xd3_config" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_config \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBwinsize\fP"
.br
.ti -1c
.RI "usize_t \fBsprevsz\fP"
.br
.ti -1c
.RI "usize_t \fBiopt_size\fP"
.br
.ti -1c
.RI "xd3_getblk_func * \fBgetblk\fP"
.br
.ti -1c
.RI "xd3_alloc_func * \fBalloc\fP"
.br
.ti -1c
.RI "xd3_free_func * \fBfreef\fP"
.br
.ti -1c
.RI "void * \fBopaque\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBxd3_sec_cfg\fP \fBsec_data\fP"
.br
.ti -1c
.RI "\fBxd3_sec_cfg\fP \fBsec_inst\fP"
.br
.ti -1c
.RI "\fBxd3_sec_cfg\fP \fBsec_addr\fP"
.br
.ti -1c
.RI "xd3_smatch_cfg \fBsmatch_cfg\fP"
.br
.ti -1c
.RI "\fBxd3_smatcher\fP \fBsmatcher_soft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 684 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
