.TH "_xd3_dinst" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_dinst \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBtype1\fP"
.br
.ti -1c
.RI "uint8_t \fBsize1\fP"
.br
.ti -1c
.RI "uint8_t \fBtype2\fP"
.br
.ti -1c
.RI "uint8_t \fBsize2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 547 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
