.TH "_xd3_addr_cache" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_addr_cache \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBs_near\fP"
.br
.ti -1c
.RI "usize_t \fBs_same\fP"
.br
.ti -1c
.RI "usize_t \fBnext_slot\fP"
.br
.ti -1c
.RI "usize_t * \fBnear_array\fP"
.br
.ti -1c
.RI "usize_t * \fBsame_array\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 600 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
