.TH "_xd3_sec_cfg" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_sec_cfg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdata_type\fP"
.br
.ti -1c
.RI "usize_t \fBngroups\fP"
.br
.ti -1c
.RI "usize_t \fBsector_size\fP"
.br
.ti -1c
.RI "int \fBinefficient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 675 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
