.TH "_xd3_whole_state" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_whole_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBaddslen\fP"
.br
.ti -1c
.RI "uint8_t * \fBadds\fP"
.br
.ti -1c
.RI "usize_t \fBadds_alloc\fP"
.br
.ti -1c
.RI "usize_t \fBinstlen\fP"
.br
.ti -1c
.RI "\fBxd3_winst\fP * \fBinst\fP"
.br
.ti -1c
.RI "usize_t \fBinst_alloc\fP"
.br
.ti -1c
.RI "usize_t \fBwininfolen\fP"
.br
.ti -1c
.RI "\fBxd3_wininfo\fP * \fBwininfo\fP"
.br
.ti -1c
.RI "usize_t \fBwininfo_alloc\fP"
.br
.ti -1c
.RI "xoff_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 654 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
