.TH "_xd3_output" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_output \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBbase\fP"
.br
.ti -1c
.RI "usize_t \fBnext\fP"
.br
.ti -1c
.RI "usize_t \fBavail\fP"
.br
.ti -1c
.RI "\fBxd3_output\fP * \fBnext_page\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 574 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
