.TH "_xd3_smatcher" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_smatcher \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBstring_match\fP )(\fBxd3_stream\fP *stream)"
.br
.ti -1c
.RI "usize_t \fBlarge_look\fP"
.br
.ti -1c
.RI "usize_t \fBlarge_step\fP"
.br
.ti -1c
.RI "usize_t \fBsmall_look\fP"
.br
.ti -1c
.RI "usize_t \fBsmall_chain\fP"
.br
.ti -1c
.RI "usize_t \fBsmall_lchain\fP"
.br
.ti -1c
.RI "usize_t \fBmax_lazy\fP"
.br
.ti -1c
.RI "usize_t \fBlong_enough\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 619 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
