.TH "_xd3_lzma_stream" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_lzma_stream \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "lzma_stream \fBlzma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file xdelta3-lzma.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
