.TH "_xd3_rinst" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_rinst \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBxtra\fP"
.br
.ti -1c
.RI "uint8_t \fBcode1\fP"
.br
.ti -1c
.RI "uint8_t \fBcode2\fP"
.br
.ti -1c
.RI "usize_t \fBpos\fP"
.br
.ti -1c
.RI "usize_t \fBsize\fP"
.br
.ti -1c
.RI "xoff_t \fBaddr\fP"
.br
.ti -1c
.RI "\fBxd3_rlist\fP \fBlink\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 534 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
