.TH "_xd3_source" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xd3_source \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "usize_t \fBblksize\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "void * \fBioh\fP"
.br
.ti -1c
.RI "xoff_t \fBmax_winsize\fP"
.br
.ti -1c
.RI "xoff_t \fBcurblkno\fP"
.br
.ti -1c
.RI "usize_t \fBonblk\fP"
.br
.ti -1c
.RI "const uint8_t * \fBcurblk\fP"
.br
.ti -1c
.RI "usize_t \fBsrclen\fP"
.br
.ti -1c
.RI "xoff_t \fBsrcbase\fP"
.br
.ti -1c
.RI "int \fBshiftby\fP"
.br
.ti -1c
.RI "int \fBmaskby\fP"
.br
.ti -1c
.RI "xoff_t \fBcpyoff_blocks\fP"
.br
.ti -1c
.RI "usize_t \fBcpyoff_blkoff\fP"
.br
.ti -1c
.RI "xoff_t \fBgetblkno\fP"
.br
.ti -1c
.RI "xoff_t \fBmax_blkno\fP"
.br
.ti -1c
.RI "xoff_t \fBfrontier_blkno\fP"
.br
.ti -1c
.RI "usize_t \fBonlastblk\fP"
.br
.ti -1c
.RI "int \fBeof_known\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 718 of file xdelta3.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
