.TH "Dynamic allocation of memory pools." 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dynamic allocation of memory pools. \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBshbuf_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBshbuf_t\fP * \fBshbuf_init\fP (void)"
.br
.ti -1c
.RI "void \fBshbuf_catstr\fP (\fBshbuf_t\fP *buf, char *data)"
.br
.RI "\fIInserts a string into a \fC\fBshbuf_t\fP\fP memory pool. \fP"
.ti -1c
.RI "void \fBshbuf_cat\fP (\fBshbuf_t\fP *buf, unsigned char *data, size_t data_len)"
.br
.ti -1c
.RI "void \fBshbuf_free\fP (\fBshbuf_t\fP **buf_p)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
