.TH "The 'sharefs' inode subsystem." 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
The 'sharefs' inode subsystem. \- 
.PP
The 'sharefs' inode subsystem.  

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBshfs_node\fP"
.br
.RI "\fIA sharefs filesystem inode. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSHINO_APP_ID\fP   100"
.br
.RI "\fIInode is in reference to an application-specific directory. \fP"
.ti -1c
.RI "#define \fBSHINO_PARTITION\fP   101"
.br
.RI "\fIInode is the root of an entire sharefs partition. \fP"
.ti -1c
.RI "#define \fBSHINO_PEER\fP   102"
.br
.RI "\fIInode is a reference to a remote sharefs partition. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef __uint64_t \fBshfs_ino\fP"
.br
.RI "\fIA sharefs inode reference definition. \fP"
.ti -1c
.RI "typedef __uint32_t \fBshfs_ino_type\fP"
.br
.RI "\fIA sharefs inode type definition. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The 'sharefs' inode subsystem. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
