.TH "shfs_node" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_node \- 
.PP
A sharefs filesystem inode.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfs.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshfs_ino\fP \fBd_ino\fP"
.br
.ti -1c
.RI "\fBshfs_ino_type\fP \fBd_type\fP"
.br
.ti -1c
.RI "off_t \fBd_off\fP"
.br
.ti -1c
.RI "unsigned short \fBd_reclen\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct in_addr \fBaddr\fP"
.br
.ti -1c
.RI "   struct in6_addr \fBaddr6\fP"
.br
.ti -1c
.RI "} \fBpeer\fP"
.br
.ti -1c
.RI "char \fBd_name\fP [4095+1]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A sharefs filesystem inode. 
.PP
Definition at line 104 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
