.TH "skbuf_s" 3 "3 Apr 2013" "Version 2.0.3" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
skbuf_s \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdata_of\fP"
.br
.ti -1c
.RI "size_t \fBdata_max\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file sockbuff.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
