.TH "Libshare_fsattr" 3 "1 Jan 2015" "Version 2.18" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fsattr \- 
.PP
Inode attributes.  

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBshfs_attr_label\fP (int attr_idx)"
.br
.ti -1c
.RI "\fBshfs_attr_t\fP \fBshfs_block_attr\fP (\fBshfs_block_t\fP *blk)"
.br
.ti -1c
.RI "\fBshfs_attr_t\fP \fBshfs_attr\fP (\fBshfs_ino_t\fP *inode)"
.br
.ti -1c
.RI "char * \fBshfs_attr_str\fP (\fBshfs_attr_t\fP attr)"
.br
.ti -1c
.RI "int \fBshfs_attr_set\fP (\fBshfs_ino_t\fP *file, int attr)"
.br
.ti -1c
.RI "int \fBshfs_attr_unset\fP (\fBshfs_ino_t\fP *file, int attr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inode attributes. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
