.TH "Libshare_fslog" 3 "30 Jan 2015" "Version 2.22" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Libshare_fslog \- 
.PP
Application logging calls.  

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBshlog\fP (int level, int err_code, char *log_str)"
.br
.ti -1c
.RI "void \fBsherr\fP (int err_code, char *log_str)"
.br
.ti -1c
.RI "void \fBshwarn\fP (char *log_str)"
.br
.ti -1c
.RI "void \fBshinfo\fP (char *log_str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application logging calls. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
