.TH "sh_sha512_t" 3 "30 Jan 2015" "Version 2.22" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sh_sha512_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBhash\fP [8]"
.br
.RI "\fI512-bit hash \fP"
.ti -1c
.RI "size_t \fBlen\fP"
.br
.RI "\fIlength of hash data \fP"
.ti -1c
.RI "uint8_t \fBblock\fP [128]"
.br
.RI "\fImessage block \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1274 of file shmem.h.
.SH "Field Documentation"
.PP 
.SS "uint8_t \fBsh_sha512_t::block\fP[128]"
.PP
message block 
.PP
Definition at line 1278 of file shmem.h.
.SS "uint64_t \fBsh_sha512_t::hash\fP[8]"
.PP
512-bit hash 
.PP
Definition at line 1276 of file shmem.h.
.SS "size_t \fBsh_sha512_t::len\fP"
.PP
length of hash data 
.PP
Definition at line 1277 of file shmem.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
