.TH "shfs_hdr_t" 3 "14 Jan 2015" "Version 2.20" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_hdr_t \- 
.PP
A sharefs filesystem inode header.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfs.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBname\fP"
.br
.RI "\fIA hashed reference of the inode. \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBowner\fP"
.br
.RI "\fIA hashed reference of the inode's owner id. \fP"
.ti -1c
.RI "\fBshsize_t\fP \fBsize\fP"
.br
.RI "\fIThe total size of the data segment being referenced. \fP"
.ti -1c
.RI "\fBshtime_t\fP \fBctime\fP"
.br
.RI "\fIThe time that the inode was created. \fP"
.ti -1c
.RI "\fBshtime_t\fP \fBmtime\fP"
.br
.RI "\fIThe last time this inode was written to. \fP"
.ti -1c
.RI "uint64_t \fBcrc\fP"
.br
.RI "\fIA crc checksum representation of the underlying data. \fP"
.ti -1c
.RI "\fBshfs_attr_t\fP \fBattr\fP"
.br
.RI "\fIA bitvector specifying inode attributes. \fP"
.ti -1c
.RI "\fBshfs_ino_type_t\fP \fBtype\fP"
.br
.RI "\fIType of inode. \fP"
.ti -1c
.RI "\fBshfs_ino_type_t\fP \fBformat\fP"
.br
.RI "\fIType of inode data contained. \fP"
.ti -1c
.RI "\fBshfs_idx_t\fP \fBpos\fP"
.br
.RI "\fIInode position in the partition. \fP"
.ti -1c
.RI "\fBshfs_idx_t\fP \fBnpos\fP"
.br
.RI "\fIThe position of the next inode in a chain. \fP"
.ti -1c
.RI "\fBshfs_idx_t\fP \fBfpos\fP"
.br
.RI "\fIThe position of the first inode in a chain. \fP"
.ti -1c
.RI "uint16_t \fB__reserved_1__\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A sharefs filesystem inode header. 

\fBSee also:\fP
.RS 4
\fBshfs_meta()\fP \fBSHINODE_DIRECTORY\fP 
.RE
.PP

.PP
Definition at line 422 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshkey_t\fP \fBshfs_hdr_t::name\fP"
.PP
A hashed reference of the inode. 
.PP
Definition at line 428 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
