.TH "shfs_ino_buf" 3 "25 Jan 2015" "Version 2.22" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_ino_buf \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshbuf_t\fP * \fBbuff\fP"
.br
.RI "\fIbuffered data segment of inode data \fP"
.ti -1c
.RI "off_t \fBbuff_of\fP"
.br
.RI "\fIoffset for data segment from beginning inode data \fP"
.ti -1c
.RI "off_t \fBbuff_pos\fP"
.br
.RI "\fIcurrent IO read/write index position of data segment (buff). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 490 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshbuf_t\fP* \fBshfs_ino_buf::buff\fP"
.PP
buffered data segment of inode data 
.PP
Definition at line 493 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
