.TH "shjson_t" 3 "19 Jun 2014" "Version 2.1.2" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shjson_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBshjson_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBshjson_t\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBshjson_t\fP * \fBchild\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBvaluestring\fP"
.br
.ti -1c
.RI "int \fBvalueint\fP"
.br
.ti -1c
.RI "double \fBvaluedouble\fP"
.br
.ti -1c
.RI "char * \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file shmem_json.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
