.TH "shkey_t" 3 "19 Jun 2014" "Version 2.1.2" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shkey_t \- 
.PP
A key used to represent a hash code of an object.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shmem_key.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBcode\fP [4]"
.br
.RI "\fIThe checksum values comprimising the key token. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A key used to represent a hash code of an object. 
.PP
Definition at line 61 of file shmem_key.h.
.SH "Field Documentation"
.PP 
.SS "uint32_t \fBshkey_t::code\fP[4]"
.PP
The checksum values comprimising the key token. \fBNote:\fP
.RS 4
This variable must be the initial variable in the structure. 
.RE
.PP

.PP
Definition at line 68 of file shmem_key.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
