.TH "shmsgq_t" 3 "3 Jan 2015" "Version 2.18" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shmsgq_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshtime_t\fP \fBlock_t\fP"
.br
.RI "\fIexpiration of lock or 0 if unlocked. \fP"
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.RI "\fImessage queue flags SHMSGF_XX \fP"
.ti -1c
.RI "uint32_t \fB__reserved_1__\fP"
.br
.ti -1c
.RI "uint32_t \fBread_idx\fP"
.br
.RI "\fIread msg seek offset \fP"
.ti -1c
.RI "uint32_t \fBwrite_idx\fP"
.br
.RI "\fIwrite msg seek offset \fP"
.ti -1c
.RI "uint32_t \fBread_of\fP"
.br
.RI "\fIread data seek offset \fP"
.ti -1c
.RI "uint32_t \fBwrite_of\fP"
.br
.RI "\fIwrite data seek offset \fP"
.ti -1c
.RI "\fBshmsg_t\fP \fBmsg\fP [2048]"
.br
.RI "\fItable of message definitions \fP"
.ti -1c
.RI "unsigned char \fBdata\fP [0]"
.br
.RI "\fIraw message content data \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 741 of file shfs.h.
.SH "Field Documentation"
.PP 
.SS "\fBshtime_t\fP \fBshmsgq_t::lock_t\fP"
.PP
expiration of lock or 0 if unlocked. 
.PP
Definition at line 743 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
