.TH "shnet_t" 3 "23 Dec 2013" "Version 2.1.2" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shnet_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBrcvbuf_len\fP"
.br
.ti -1c
.RI "int \fBsndbuf_len\fP"
.br
.ti -1c
.RI "\fBshbuf_t\fP * \fBrecv_buff\fP"
.br
.ti -1c
.RI "\fBshbuf_t\fP * \fBsend_buff\fP"
.br
.ti -1c
.RI "struct sockaddr_in \fBaddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file shnet.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
