.TH "shpeer_t" 3 "6 Dec 2014" "Version 2.17" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpeer_t \- 
.PP
A local or remote reference to a libshare runtime enabled application.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shpeer.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshpeer_addr_t\fP \fBaddr\fP"
.br
.RI "\fIA IP 4/6 network address. \fP"
.ti -1c
.RI "uint16_t \fBpid\fP"
.br
.RI "\fIThe local process id. \fP"
.ti -1c
.RI "char \fBlabel\fP [16]"
.br
.RI "\fIA label identifying a perspective view of the peer. \fP"
.ti -1c
.RI "uint32_t \fBuid\fP"
.br
.RI "\fIThe client user ID that is associated with the peer. \fP"
.ti -1c
.RI "uint32_t \fBarch\fP"
.br
.RI "\fIArchitecture of local machine for private key generation. \fP"
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.RI "\fIA SHNET_PEER_XX type. \fP"
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.RI "\fIbehaviour control \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBname\fP"
.br
.RI "\fIA key reference to the peer identify. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A local or remote reference to a libshare runtime enabled application. 

 
 See the libshare_net.3 API man page for ESP protocol network operations.
  
.PP
\fBNote:\fP
.RS 4
Addresses are stored in network byte order. 
.RE
.PP

.PP
\fBExamples: \fP
.in +1c
.PP
\fBshkeystore.c\fP.
.PP
Definition at line 102 of file shpeer.h.
.SH "Field Documentation"
.PP 
.SS "\fBshpeer_addr_t\fP \fBshpeer_t::addr\fP"
.PP
A IP 4/6 network address. 
.PP
Definition at line 107 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::arch\fP"
.PP
Architecture of local machine for private key generation. 
.PP
Definition at line 127 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::flags\fP"
.PP
behaviour control 
.PP
Definition at line 137 of file shpeer.h.
.SS "char \fBshpeer_t::label\fP[16]"
.PP
A label identifying a perspective view of the peer. 
.PP
Definition at line 117 of file shpeer.h.
.SS "\fBshkey_t\fP \fBshpeer_t::name\fP"
.PP
A key reference to the peer identify. 
.PP
Definition at line 142 of file shpeer.h.
.SS "uint16_t \fBshpeer_t::pid\fP"
.PP
The local process id. 
.PP
Definition at line 112 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::type\fP"
.PP
A SHNET_PEER_XX type. 
.PP
Definition at line 132 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::uid\fP"
.PP
The client user ID that is associated with the peer. 
.PP
Definition at line 122 of file shpeer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
