.TH "shpeer_t" 3 "15 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shpeer_t \- 
.PP
The local or remote machine commonly associated with a sharefs partition.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shpeer.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   uint32_t \fBip\fP"
.br
.ti -1c
.RI "   uint64_t \fBip6\fP"
.br
.ti -1c
.RI "} \fBaddr\fP"
.br
.RI "\fIA IP 4/6 network address. \fP"
.ti -1c
.RI "uint8_t \fBhwaddr\fP [6]"
.br
.RI "\fIThe network hardware address associated with the peer. \fP"
.ti -1c
.RI "char \fBlabel\fP [16]"
.br
.RI "\fIA label identifying a perspective view of the peer. \fP"
.ti -1c
.RI "uint32_t \fBuid\fP"
.br
.RI "\fIThe client user ID that is associated with the peer. \fP"
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.RI "\fIA SHNET_PEER_XX type. \fP"
.ti -1c
.RI "\fBshkey_t\fP \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The local or remote machine commonly associated with a sharefs partition. 

 
 See the libshare_net.3 API man page for ESP protocol network operations.
  
.PP
\fBNote:\fP
.RS 4
Addresses are stored in network byte order. 
.RE
.PP

.PP
\fBExamples: \fP
.in +1c
.PP
\fBshfs_inode_remote_copy.c\fP, and \fBshkeystore.c\fP.
.PP
Definition at line 80 of file shpeer.h.
.SH "Field Documentation"
.PP 
.SS "union { ... }   \fBshpeer_t::addr\fP"
.PP
A IP 4/6 network address. 
.SS "uint8_t \fBshpeer_t::hwaddr\fP[6]"
.PP
The network hardware address associated with the peer. 
.PP
Definition at line 93 of file shpeer.h.
.SS "char \fBshpeer_t::label\fP[16]"
.PP
A label identifying a perspective view of the peer. 
.PP
Definition at line 98 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::type\fP"
.PP
A SHNET_PEER_XX type. 
.PP
Definition at line 108 of file shpeer.h.
.SS "uint32_t \fBshpeer_t::uid\fP"
.PP
The client user ID that is associated with the peer. 
.PP
Definition at line 103 of file shpeer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
