.TH "shsig_t" 3 "15 Nov 2014" "Version 2.16" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shsig_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshkey_t\fP \fBsig_id\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBsig_peer\fP"
.br
.ti -1c
.RI "\fBshkey_t\fP \fBsig_key\fP"
.br
.ti -1c
.RI "\fBshtime_t\fP \fBsig_stamp\fP"
.br
.ti -1c
.RI "uint32_t \fBsig_expire\fP"
.br
.ti -1c
.RI "uint32_t \fBsig_ref\fP"
.br
.ti -1c
.RI "char \fBsig_tx\fP [136]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 692 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
