#!/bin/bash

#  Copyright 2013 Brian Burrell 
#
#  This file is part of the Share Library.
#  (https://github.com/briburrell/share)
#        
#  The Share Library is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version. 
#
#  The Share Library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with The Share Library.  If not, see <http://www.gnu.org/licenses/>.

if [ -e "/usr/share/sharelib/share.inc" ] ; then
. /usr/share/sharelib/share.inc
fi

if [ -e "/usr/local/share/sharelib/share.inc" ] ; then
. /usr/local/share/sharelib/share.inc
fi

if [ -e "./share.inc" ] ; then
. ./share.inc
fi

if [ "$1" = "" ] ; then
  echo "version $VERSION (sharelib)"
  echo "usage: $0 <file> [<file>..]"
  echo ""
  echo "Prints the contents of a file on a sharefs file."
  echo "Relative path is based on the current working directory."
  echo ""
  echo "Copyright 2013 Brian Burrell"
  echo "Licensed under the GNU GENERAL PUBLIC LICENSE Version 3"
  echo "Visit 'https://github.com/briburrell/share' for more information."
  exit 0;
fi

PATH=".:$PATH"

for arg in "$@"
do
  shnet file print -f$arg
done


