.TH "Hashmaps and memory pools." 3 "9 Apr 2013" "Version 2.0.5" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hashmaps and memory pools. \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDynamic Memory Buffers\fP"
.br
.ti -1c
.RI "\fBMeta Definition Hashmaps\fP"
.br
.ti -1c
.RI "\fBMemory Buffer Pools\fP"
.br
.PP

.RI "\fIThe libshare memory buffer pool allocation utilities. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
