.TH "Memory Buffer Pools" 3 "9 Apr 2013" "Version 2.0.5" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Memory Buffer Pools \- 
.PP
The libshare memory buffer pool allocation utilities.  
The libshare memory buffer pool allocation utilities. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
