.TH "Network socket operations." 3 "8 Apr 2013" "Version 2.0.5" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network socket operations. \- 
.PP
The libshare Socket Handling provides access to regular socket operations with posix or convienence functions in addition to access to the ESP network protocol.  

.SS "Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBshwrite\fP (int fd, const void *buf, size_t count)"
.br
.RI "\fIWrite data to a socket. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The libshare Socket Handling provides access to regular socket operations with posix or convienence functions in addition to access to the ESP network protocol. 

The ESP protocol performs streaming compression and provides more security than TCP. The libshare network socket operations. 
.SH "Function Documentation"
.PP 
.SS "ssize_t shwrite (int fd, const void * buf, size_t count)"
.PP
Write data to a socket. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
