.TH "shbuf_t" 3 "6 Apr 2013" "Version 2.0.5" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shbuf_t \- 
.PP
A memory buffer.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shbuf.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdata_of\fP"
.br
.ti -1c
.RI "size_t \fBdata_max\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A memory buffer. 
.PP
Definition at line 43 of file shbuf.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
