.TH "shfs_t" 3 "6 Apr 2013" "Version 2.0.5" "libshare" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shfs_t \- 
.PP
The sharefs filesystem structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shfs.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBflags\fP"
.br
.RI "\fIThe flags associated with the sharefs partition. \fP"
.ti -1c
.RI "\fBshpeer_t\fP \fBpeer\fP"
.br
.RI "\fIA remote peer associated with the sharefs file-system. \fP"
.ti -1c
.RI "\fBshfs_ino_t\fP * \fBbase_ino\fP"
.br
.RI "\fIRoot directory. \fP"
.ti -1c
.RI "\fBshfs_ino_t\fP * \fBcur_ino\fP"
.br
.RI "\fIApplication's current working directory. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The sharefs filesystem structure. 

\fBNote:\fP
.RS 4
See also: \fC\fBshfs_ino_t\fP\fP 
.RE
.PP

.PP
\fBExamples: \fP
.in +1c
.PP
\fBshfs_inode_mkdir.c\fP, \fBshfs_inode_remote_copy.c\fP, and \fBshfs_inode_remote_link.c\fP.
.PP
Definition at line 292 of file shfs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libshare from the source code.
