/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_PHPSHARE_H
#define PHP_PHPSHARE_H

extern zend_module_entry phpshare_module_entry;
#define phpext_phpshare_ptr &phpshare_module_entry

#ifdef PHP_WIN32
# define PHP_PHPSHARE_API __declspec(dllexport)
#else
# define PHP_PHPSHARE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(phpshare);
PHP_MSHUTDOWN_FUNCTION(phpshare);
PHP_RINIT_FUNCTION(phpshare);
PHP_RSHUTDOWN_FUNCTION(phpshare);
PHP_MINFO_FUNCTION(phpshare);

ZEND_NAMED_FUNCTION(_wrap_test_main);
ZEND_NAMED_FUNCTION(_wrap_shbuf_init);
ZEND_NAMED_FUNCTION(_wrap_shbuf_catstr);
ZEND_NAMED_FUNCTION(_wrap_shbuf_cat);
ZEND_NAMED_FUNCTION(_wrap_shbuf_size);
ZEND_NAMED_FUNCTION(_wrap_shbuf_clear);
ZEND_NAMED_FUNCTION(_wrap_shbuf_trim);
ZEND_NAMED_FUNCTION(_wrap_shbuf_free);
ZEND_NAMED_FUNCTION(_wrap_shtime);
ZEND_NAMED_FUNCTION(_wrap_shtime64);
ZEND_NAMED_FUNCTION(_wrap_shfs_dir_base);
ZEND_NAMED_FUNCTION(_wrap_shfs_dir_cwd);
ZEND_NAMED_FUNCTION(_wrap_shfs_dir_parent);
ZEND_NAMED_FUNCTION(_wrap_shfs_dir_entry);
ZEND_NAMED_FUNCTION(_wrap_shfs_app_name);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_tree);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_root);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_parent);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_write_entity);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_write_block);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_write);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_read_block);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_read);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_filename);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_filename_set);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_name);
ZEND_NAMED_FUNCTION(_wrap_shfs_inode_path);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_tree);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_path);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_open);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_free);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_index);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_scan);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_write);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_grow);
ZEND_NAMED_FUNCTION(_wrap_shfs_journal_close);
ZEND_NAMED_FUNCTION(_wrap_shfs_meta);
ZEND_NAMED_FUNCTION(_wrap_shfs_meta_save);
ZEND_NAMED_FUNCTION(_wrap_shfs_init);
ZEND_NAMED_FUNCTION(_wrap_shfs_free);
ZEND_NAMED_FUNCTION(_wrap_shfs_partition_id);
ZEND_NAMED_FUNCTION(_wrap_shfs_proc_lock);
ZEND_NAMED_FUNCTION(_wrap_shfs_read_mem);
ZEND_NAMED_FUNCTION(_wrap_shfs_write_mem);
ZEND_NAMED_FUNCTION(_wrap_shfs_write_print);
ZEND_NAMED_FUNCTION(_wrap_shkey_bin);
ZEND_NAMED_FUNCTION(_wrap_shkey_str);
ZEND_NAMED_FUNCTION(_wrap_shkey_num);
ZEND_NAMED_FUNCTION(_wrap_shkey_uniq);
ZEND_NAMED_FUNCTION(_wrap_shkey_free);
ZEND_NAMED_FUNCTION(_wrap_shkey_print);
ZEND_NAMED_FUNCTION(_wrap_shmeta_init);
ZEND_NAMED_FUNCTION(_wrap_shmeta_free);
ZEND_NAMED_FUNCTION(_wrap_shmetafunc_default);
ZEND_NAMED_FUNCTION(_wrap_shmeta_set);
ZEND_NAMED_FUNCTION(_wrap_shmeta_set_str);
ZEND_NAMED_FUNCTION(_wrap_shmeta_unset_str);
ZEND_NAMED_FUNCTION(_wrap_shmeta_set_void);
ZEND_NAMED_FUNCTION(_wrap_shmeta_unset_void);
ZEND_NAMED_FUNCTION(_wrap_shmeta_get_str);
ZEND_NAMED_FUNCTION(_wrap_shmeta_get_void);
ZEND_NAMED_FUNCTION(_wrap_shmeta_get);
ZEND_NAMED_FUNCTION(_wrap_shmeta_print);
ZEND_NAMED_FUNCTION(_wrap_shlock_open);
ZEND_NAMED_FUNCTION(_wrap_shlock_tryopen);
ZEND_NAMED_FUNCTION(_wrap_shlock_close);
ZEND_NAMED_FUNCTION(_wrap_shlock_destroy);
ZEND_NAMED_FUNCTION(_wrap_shencode);
ZEND_NAMED_FUNCTION(_wrap_shencode_str);
ZEND_NAMED_FUNCTION(_wrap_shdecode);
ZEND_NAMED_FUNCTION(_wrap_shdecode_str);
ZEND_NAMED_FUNCTION(_wrap_shkey_cmp);
ZEND_NAMED_FUNCTION(_wrap_shpool_init);
ZEND_NAMED_FUNCTION(_wrap_shpool_size);
ZEND_NAMED_FUNCTION(_wrap_shpool_grow);
ZEND_NAMED_FUNCTION(_wrap_shpool_get);
ZEND_NAMED_FUNCTION(_wrap_shpool_get_index);
ZEND_NAMED_FUNCTION(_wrap_shpool_put);
ZEND_NAMED_FUNCTION(_wrap_shpool_free);
ZEND_NAMED_FUNCTION(_wrap_shnet_accept);
ZEND_NAMED_FUNCTION(_wrap_shnet_bindsk);
ZEND_NAMED_FUNCTION(_wrap_shnet_bind);
ZEND_NAMED_FUNCTION(_wrap_shnet_close);
ZEND_NAMED_FUNCTION(_wrap_shnet_conn);
ZEND_NAMED_FUNCTION(_wrap_shnet_fcntl);
ZEND_NAMED_FUNCTION(_wrap_shnet_gethostbyname);
ZEND_NAMED_FUNCTION(_wrap_shnet_peer);
ZEND_NAMED_FUNCTION(_wrap_shnet_read);
ZEND_NAMED_FUNCTION(_wrap_shnet_verify);
ZEND_NAMED_FUNCTION(_wrap_shnet_select);
ZEND_NAMED_FUNCTION(_wrap_shnet_sk);
ZEND_NAMED_FUNCTION(_wrap_shnet_socket);
ZEND_NAMED_FUNCTION(_wrap_shnet_write);
#endif /* PHP_PHPSHARE_H */
