/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package libshare;

public class jshareJNI {
  public final static native void test_main();
  public final static native long shbuf_init();
  public final static native void shbuf_catstr(long jarg1, String jarg2);
  public final static native void shbuf_cat(long jarg1, long jarg2, long jarg3);
  public final static native long shbuf_size(long jarg1);
  public final static native void shbuf_clear(long jarg1);
  public final static native void shbuf_trim(long jarg1, long jarg2);
  public final static native void shbuf_free(long jarg1);
  public final static native double shtime();
  public final static native long shtime64();
  public final static native long shkey_bin(String jarg1, long jarg2);
  public final static native long shkey_str(String jarg1);
  public final static native long shkey_num(int jarg1);
  public final static native long shkey_uniq();
  public final static native void shkey_free(long jarg1);
  public final static native String shkey_print(long jarg1);
  public final static native long shmeta_init();
  public final static native void shmeta_free(long jarg1);
  public final static native long shmetafunc_default(String jarg1, long jarg2);
  public final static native void shmeta_set(long jarg1, long jarg2, long jarg3);
  public final static native void shmeta_set_str(long jarg1, long jarg2, String jarg3);
  public final static native void shmeta_unset_str(long jarg1, long jarg2);
  public final static native void shmeta_set_void(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native void shmeta_unset_void(long jarg1, long jarg2);
  public final static native String shmeta_get_str(long jarg1, long jarg2);
  public final static native long shmeta_get_void(long jarg1, long jarg2);
  public final static native long shmeta_get(long jarg1, long jarg2);
  public final static native void shmeta_print(long jarg1, long jarg2);
  public final static native long shlock_open(long jarg1, int jarg2);
  public final static native int shlock_tryopen(long jarg1, int jarg2, long jarg3);
  public final static native int shlock_close(long jarg1);
  public final static native void shlock_destroy();
  public final static native int shencode(String jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long shencode_str(String jarg1);
  public final static native int shdecode(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int shdecode_str(String jarg1, long jarg2);
  public final static native int shkey_cmp(long jarg1, long jarg2);
  public final static native long shpool_init();
  public final static native long shpool_size(long jarg1);
  public final static native void shpool_grow(long jarg1);
  public final static native long shpool_get(long jarg1);
  public final static native long shpool_get_index(long jarg1, int jarg2);
  public final static native void shpool_put(long jarg1, long jarg2);
  public final static native void shpool_free(long jarg1);
  public final static native int shnet_accept(int jarg1);
  public final static native int shnet_bindsk(int jarg1, String jarg2, long jarg3);
  public final static native int shnet_bind(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_close(int jarg1);
  public final static native int shnet_conn(int jarg1, String jarg2, int jarg3, int jarg4);
  public final static native int shnet_fcntl(int jarg1, int jarg2, int jarg3);
  public final static native long shnet_gethostbyname(String jarg1);
  public final static native long shnet_peer(String jarg1);
  public final static native long shnet_read(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_verify(long jarg1, long jarg2, long jarg3);
  public final static native int shnet_select(int jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int shnet_sk();
  public final static native int shnet_socket(int jarg1, int jarg2, int jarg3);
  public final static native long shnet_write(int jarg1, long jarg2, long jarg3);
}
