/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


/* header files andfunc decls */
#include "share.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_libshare_jshareJNI_test_1main(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  test_main();
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shbuf_1init(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  shbuf_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (shbuf_t *)shbuf_init();
  *(shbuf_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shbuf_1catstr(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  shbuf_t *arg1 = (shbuf_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  shbuf_catstr(arg1,arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shbuf_1cat(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  shbuf_t *arg1 = (shbuf_t *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  shbuf_cat(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shbuf_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shbuf_t *arg1 = (shbuf_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t **)&jarg1; 
  result = shbuf_size(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shbuf_1clear(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shbuf_t *arg1 = (shbuf_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t **)&jarg1; 
  shbuf_clear(arg1);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shbuf_1trim(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shbuf_t *arg1 = (shbuf_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  shbuf_trim(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shbuf_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shbuf_t **arg1 = (shbuf_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shbuf_t ***)&jarg1; 
  shbuf_free(arg1);
}


SWIGEXPORT jdouble JNICALL Java_libshare_jshareJNI_shtime(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)shtime();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shtime64(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  shtime_t result;
  
  (void)jenv;
  (void)jcls;
  result = shtime64();
  {
    shtime_t * resultptr = (shtime_t *) malloc(sizeof(shtime_t));
    memmove(resultptr, &result, sizeof(shtime_t));
    *(shtime_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1dir_1base(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  result = (shfs_ino_t *)shfs_dir_base(arg1);
  *(shfs_ino_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1dir_1cwd(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  result = (shfs_ino_t *)shfs_dir_cwd(arg1);
  *(shfs_ino_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1dir_1parent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (shfs_ino_t *)shfs_dir_parent(arg1);
  *(shfs_ino_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1dir_1entry(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  char *arg2 = (char *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (shfs_ino_t *)shfs_dir_entry(arg1,arg2);
  *(shfs_ino_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shfs_1app_1name(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)shfs_app_name(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (int)jarg3; 
  result = (shfs_ino_t *)shfs_inode(arg1,arg2,arg3);
  *(shfs_ino_t **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode_1tree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  shfs_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (shfs_t *)shfs_inode_tree(arg1);
  *(shfs_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode_1root(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (shfs_ino_t *)shfs_inode_root(arg1);
  *(shfs_ino_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode_1parent(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  shfs_ino_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (shfs_ino_t *)shfs_inode_parent(arg1);
  *(shfs_ino_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1inode_1write_1entity(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  result = (int)shfs_inode_write_entity(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1inode_1write_1block(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jstring jarg4, jlong jarg5) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_hdr_t *arg2 = (shfs_hdr_t *) 0 ;
  shfs_hdr_t *arg3 = (shfs_hdr_t *) 0 ;
  char *arg4 = (char *) 0 ;
  size_t arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_hdr_t **)&jarg2; 
  arg3 = *(shfs_hdr_t **)&jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return 0;
  }
  arg5 = (size_t)jarg5; 
  result = (int)shfs_inode_write_block(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode_1write(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  char *arg3 = (char *) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  result = shfs_inode_write(arg1,arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1inode_1read_1block(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_hdr_t *arg2 = (shfs_hdr_t *) 0 ;
  shfs_ino_t *arg3 = (shfs_ino_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_hdr_t **)&jarg2; 
  arg3 = *(shfs_ino_t **)&jarg3; 
  result = (int)shfs_inode_read_block(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1inode_1read(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  shbuf_t *arg3 = (shbuf_t *) 0 ;
  size_t arg4 ;
  size_t arg5 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  arg3 = *(shbuf_t **)&jarg3; 
  arg4 = (size_t)jarg4; 
  arg5 = (size_t)jarg5; 
  result = shfs_inode_read(arg1,arg2,arg3,arg4,arg5);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shfs_1inode_1filename(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)shfs_inode_filename(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shfs_1inode_1filename_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  shfs_inode_filename_set(arg1,arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shfs_1inode_1name(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (char *)shfs_inode_name(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shfs_1inode_1path(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (char *)shfs_inode_path(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1journal_1tree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_journal_t *arg1 = (shfs_journal_t *) 0 ;
  shfs_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_journal_t **)&jarg1; 
  result = (shfs_t *)shfs_journal_tree(arg1);
  *(shfs_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shfs_1journal_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jstring jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  int arg2 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (char *)shfs_journal_path(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1journal_1open(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  int arg2 ;
  shfs_journal_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (shfs_journal_t *)shfs_journal_open(arg1,arg2);
  *(shfs_journal_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shfs_1journal_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_journal_t **arg2 = (shfs_journal_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_journal_t ***)&jarg2; 
  shfs_journal_free(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1journal_1index(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  shfs_ino_t *arg1 = (shfs_ino_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_ino_t **)&jarg1; 
  result = (int)shfs_journal_index(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1journal_1scan(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)shfs_journal_scan(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1journal_1write(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  shfs_journal_t *arg1 = (shfs_journal_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_journal_t **)&jarg1; 
  result = (int)shfs_journal_write(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1journal_1grow(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  shfs_journal_t **arg1 = (shfs_journal_t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_journal_t ***)&jarg1; 
  result = (int)shfs_journal_grow(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1journal_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  shfs_journal_t **arg1 = (shfs_journal_t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_journal_t ***)&jarg1; 
  result = (int)shfs_journal_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1meta(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  shmeta_t **arg3 = (shmeta_t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  arg3 = *(shmeta_t ***)&jarg3; 
  result = (int)shfs_meta(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1meta_1save(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  shmeta_t *arg3 = (shmeta_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  arg3 = *(shmeta_t **)&jarg3; 
  result = (int)shfs_meta_save(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1init(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int arg2 ;
  shfs_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (int)jarg2; 
  result = (shfs_t *)shfs_init(arg1,arg2);
  *(shfs_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shfs_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shfs_t **arg1 = (shfs_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t ***)&jarg1; 
  shfs_free(arg1);
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shfs_1partition_1id(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  result = (shkey_t *)shfs_partition_id(arg1);
  *(shkey_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1proc_1lock(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)shfs_proc_lock(arg1,arg2);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1read_1mem(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char **arg2 = (char **) 0 ;
  size_t *arg3 = (size_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(char ***)&jarg2; 
  arg3 = *(size_t **)&jarg3; 
  result = (int)shfs_read_mem(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1write_1mem(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = (int)shfs_write_mem(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shfs_1write_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
  jint jresult = 0 ;
  shfs_t *arg1 = (shfs_t *) 0 ;
  shfs_ino_t *arg2 = (shfs_ino_t *) 0 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shfs_t **)&jarg1; 
  arg2 = *(shfs_ino_t **)&jarg2; 
  arg3 = (int)jarg3; 
  result = (int)shfs_write_print(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shkey_1bin(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  result = (shkey_t *)shkey_bin(arg1,arg2);
  *(shkey_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shkey_1str(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (shkey_t *)shkey_str(arg1);
  *(shkey_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shkey_1num(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  long arg1 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (long)jarg1; 
  result = (shkey_t *)shkey_num(arg1);
  *(shkey_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shkey_1uniq(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (shkey_t *)shkey_uniq();
  *(shkey_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shkey_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shkey_t **arg1 = (shkey_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t ***)&jarg1; 
  shkey_free(arg1);
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shkey_1print(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  shkey_t *arg1 = (shkey_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t **)&jarg1; 
  result = (char *)shkey_print(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shmeta_1init(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  shmeta_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (shmeta_t *)shmeta_init();
  *(shmeta_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shmeta_t **arg1 = (shmeta_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t ***)&jarg1; 
  shmeta_free(arg1);
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shmetafunc_1default(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  ssize_t *arg2 = (ssize_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(ssize_t **)&jarg2; 
  result = (unsigned int)shmetafunc_default((char const *)arg1,arg2);
  jresult = (jlong)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  void *arg3 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  arg3 = *(void **)&jarg3; 
  shmeta_set(arg1,arg2,(void const *)arg3);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1set_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  char *arg3 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return ;
  }
  shmeta_set_str(arg1,arg2,arg3);
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1unset_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  shmeta_unset_str(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1set_1void(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  shmeta_set_void(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1unset_1void(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  shmeta_unset_void(arg1,arg2);
}


SWIGEXPORT jstring JNICALL Java_libshare_jshareJNI_shmeta_1get_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jstring jresult = 0 ;
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  result = (char *)shmeta_get_str(arg1,arg2);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shmeta_1get_1void(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  result = (void *)shmeta_get_void(arg1,arg2);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shmeta_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  result = (void *)shmeta_get(arg1,arg2);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shmeta_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shmeta_t *arg1 = (shmeta_t *) 0 ;
  shbuf_t *arg2 = (shbuf_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shmeta_t **)&jarg1; 
  arg2 = *(shbuf_t **)&jarg2; 
  shmeta_print(arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shlock_1open(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  shkey_t *arg1 = (shkey_t *) 0 ;
  int arg2 ;
  shlock_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (shlock_t *)shlock_open(arg1,arg2);
  *(shlock_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shlock_1tryopen(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3) {
  jint jresult = 0 ;
  shkey_t *arg1 = (shkey_t *) 0 ;
  int arg2 ;
  shlock_t **arg3 = (shlock_t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(shlock_t ***)&jarg3; 
  result = (int)shlock_tryopen(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shlock_1close(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  shkey_t *arg1 = (shkey_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t **)&jarg1; 
  result = (int)shlock_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shlock_1destroy(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  shlock_destroy();
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shencode(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  size_t arg2 ;
  uint8_t **arg3 = (uint8_t **) 0 ;
  uint32_t *arg4 = (uint32_t *) 0 ;
  shkey_t *arg5 = (shkey_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = (size_t)jarg2; 
  arg3 = *(uint8_t ***)&jarg3; 
  arg4 = *(uint32_t **)&jarg4; 
  arg5 = *(shkey_t **)&jarg5; 
  result = (int)shencode(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shencode_1str(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  shkey_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (shkey_t *)shencode_str(arg1);
  *(shkey_t **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shdecode(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  uint8_t *arg1 = (uint8_t *) 0 ;
  uint32_t arg2 ;
  char **arg3 = (char **) 0 ;
  size_t *arg4 = (size_t *) 0 ;
  shkey_t *arg5 = (shkey_t *) 0 ;
  uint32_t *argp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint8_t **)&jarg1; 
  argp2 = *(uint32_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(char ***)&jarg3; 
  arg4 = *(size_t **)&jarg4; 
  arg5 = *(shkey_t **)&jarg5; 
  result = (int)shdecode(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shdecode_1str(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(shkey_t **)&jarg2; 
  result = (int)shdecode_str(arg1,arg2);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shkey_1cmp(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  shkey_t *arg1 = (shkey_t *) 0 ;
  shkey_t *arg2 = (shkey_t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shkey_t **)&jarg1; 
  arg2 = *(shkey_t **)&jarg2; 
  result = (int)shkey_cmp(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shpool_1init(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  shpool_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (shpool_t *)shpool_init();
  *(shpool_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shpool_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shpool_t *arg1 = (shpool_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t **)&jarg1; 
  result = shpool_size(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shpool_1grow(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shpool_t *arg1 = (shpool_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t **)&jarg1; 
  shpool_grow(arg1);
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shpool_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  shpool_t *arg1 = (shpool_t *) 0 ;
  shbuf_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t **)&jarg1; 
  result = (shbuf_t *)shpool_get(arg1);
  *(shbuf_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shpool_1get_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  shpool_t *arg1 = (shpool_t *) 0 ;
  int arg2 ;
  shbuf_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (shbuf_t *)shpool_get_index(arg1,arg2);
  *(shbuf_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shpool_1put(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  shpool_t *arg1 = (shpool_t *) 0 ;
  shbuf_t *arg2 = (shbuf_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t **)&jarg1; 
  arg2 = *(shbuf_t **)&jarg2; 
  shpool_put(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_libshare_jshareJNI_shpool_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  shpool_t **arg1 = (shpool_t **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(shpool_t ***)&jarg1; 
  shpool_free(arg1);
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1accept(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)shnet_accept(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1bindsk(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jlong jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  unsigned int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (unsigned int)jarg3; 
  result = (int)shnet_bindsk(arg1,arg2,arg3);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1bind(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  struct sockaddr *arg2 = (struct sockaddr *) 0 ;
  socklen_t arg3 ;
  socklen_t *argp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(struct sockaddr **)&jarg2; 
  argp3 = *(socklen_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null socklen_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (int)shnet_bind(arg1,(struct sockaddr const *)arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1close(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  int arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int)shnet_close(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1conn(JNIEnv *jenv, jclass jcls, jint jarg1, jstring jarg2, jint jarg3, jint jarg4) {
  jint jresult = 0 ;
  int arg1 ;
  char *arg2 = (char *) 0 ;
  unsigned short arg3 ;
  int arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  arg3 = (unsigned short)jarg3; 
  arg4 = (int)jarg4; 
  result = (int)shnet_conn(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1fcntl(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  long arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (long)jarg3; 
  result = (int)shnet_fcntl(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shnet_1gethostbyname(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct hostent *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct hostent *)shnet_gethostbyname(arg1);
  *(struct hostent **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shnet_1peer(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct hostent *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct hostent *)shnet_peer(arg1);
  *(struct hostent **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shnet_1read(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = shnet_read(arg1,(void const *)arg2,arg3);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1verify(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  fd_set *arg1 = (fd_set *) 0 ;
  fd_set *arg2 = (fd_set *) 0 ;
  long *arg3 = (long *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(fd_set **)&jarg1; 
  arg2 = *(fd_set **)&jarg2; 
  arg3 = *(long **)&jarg3; 
  result = (int)shnet_verify(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1select(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  int arg1 ;
  fd_set *arg2 = (fd_set *) 0 ;
  fd_set *arg3 = (fd_set *) 0 ;
  fd_set *arg4 = (fd_set *) 0 ;
  struct timeval *arg5 = (struct timeval *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(fd_set **)&jarg2; 
  arg3 = *(fd_set **)&jarg3; 
  arg4 = *(fd_set **)&jarg4; 
  arg5 = *(struct timeval **)&jarg5; 
  result = (int)shnet_select(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1sk(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)shnet_sk();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_libshare_jshareJNI_shnet_1socket(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jint jarg3) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  result = (int)shnet_socket(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_libshare_jshareJNI_shnet_1write(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  int arg1 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  ssize_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  result = shnet_write(arg1,(void const *)arg2,arg3);
  {
    ssize_t * resultptr = (ssize_t *) malloc(sizeof(ssize_t));
    memmove(resultptr, &result, sizeof(ssize_t));
    *(ssize_t **)&jresult = resultptr;
  }
  return jresult;
}


#ifdef __cplusplus
}
#endif

