/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sharelib;

class share_javaJNI {

  static {
    try {
        System.loadLibrary("share_java");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int test_main();
  public final static native String get_libshare_email();
  public final static native String get_libshare_version();
  public final static native String get_libshare_title();
  public final static native String get_libshare_path();
  public final static native java.math.BigInteger shcrc(long jarg1, int jarg2);
  public final static native long shpeer();
  public final static native long ashpeer();
  public final static native void shpeer_free(long jarg1);
  public final static native void shpref_free();
  public final static native String shpref_get(String jarg1, String jarg2);
  public final static native int shpref_set(String jarg1, String jarg2);
  public final static native double shtimef();
  public final static native long shtime();
  public final static native String shctime(long jarg1);
  public final static native long shutime(long jarg1);
  public final static native long shtimeu(long jarg1);
  public final static native String shstrtime(long jarg1, String jarg2);
  public final static native void shbuf_append(long jarg1, long jarg2);
  public final static native long shbuf_clone(long jarg1);
  public final static native void shbuf_memcpy(long jarg1, byte[] jarg2);
  public final static native long shbuf_init();
  public final static native void shbuf_catstr(long jarg1, String jarg2);
  public final static native void shbuf_cat(long jarg1, byte[] jarg2);
  public final static native long shbuf_size(long jarg1);
  public final static native long shbuf_data(long jarg1);
  public final static native void shbuf_clear(long jarg1);
  public final static native void shbuf_trim(long jarg1, long jarg2);
  public final static native void shbuf_dealloc(long jarg1);
  public final static native int shmsgget(long jarg1);
  public final static native int shmsgsnd(int jarg1, long jarg2, long jarg3);
  public final static native int shmsgrcv(int jarg1, long jarg2, long jarg3);
  public final static native int shmsgctl(int jarg1, int jarg2, int jarg3);
  public final static native String shfs_app_name(String jarg1);
  public final static native java.math.BigInteger shfs_crc(long jarg1);
  public final static native long shfs_size(long jarg1);
  public final static native long shfs_init(long jarg1);
  public final static native void shfs_free(long jarg1);
  public final static native long shfs_dir_base(long jarg1);
  public final static native long shfs_dir_parent(long jarg1);
  public final static native long shfs_dir_entry(long jarg1, String jarg2);
  public final static native long shfs_dir_find(long jarg1, String jarg2);
  public final static native int shfs_meta(long jarg1, long jarg2, long jarg3);
  public final static native int shfs_meta_save(long jarg1, long jarg2, long jarg3);
  public final static native String shfs_meta_get(long jarg1, String jarg2);
  public final static native int shfs_meta_perm(long jarg1, String jarg2, long jarg3);
  public final static native int shfs_meta_set(long jarg1, String jarg2, String jarg3);
  public final static native int shfs_sig_gen(long jarg1, long jarg2);
  public final static native int shfs_sig_get(long jarg1, long jarg2);
  public final static native int shfs_sig_verify(long jarg1, long jarg2);
  public final static native int shfs_read_mem(String jarg1, long jarg2, long jarg3);
  public final static native int shfs_write_mem(String jarg1, byte[] jarg2);
  public final static native long shfs_file_find(long jarg1, String jarg2);
  public final static native int shfs_file_pipe(long jarg1, int jarg2);
  public final static native void sherr(int jarg1, String jarg2);
  public final static native void shwarn(String jarg1);
  public final static native void shinfo(String jarg1);
  public final static native int shnet_accept(int jarg1);
  public final static native int shnet_bindsk(int jarg1, String jarg2, long jarg3);
  public final static native int shnet_bind(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_close(int jarg1);
  public final static native int shnet_conn(int jarg1, String jarg2, int jarg3, int jarg4);
  public final static native int shnet_fcntl(int jarg1, int jarg2, int jarg3);
  public final static native long shnet_gethostbyname(String jarg1);
  public final static native long shnet_peer(String jarg1);
  public final static native long shnet_read(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_sk();
  public final static native int shnet_socket(int jarg1, int jarg2, int jarg3);
  public final static native long shnet_host(int jarg1);
  public final static native long shnet_write(int jarg1, long jarg2, long jarg3);
  public final static native int shnet_verify(long jarg1, long jarg2, long jarg3);
  public final static native int shnet_select(int jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long shkey_bin(String jarg1, long jarg2);
  public final static native long shkey_str(String jarg1);
  public final static native long shkey_num(int jarg1);
  public final static native long shkey_uniq();
  public final static native void shkey_free(long jarg1);
  public final static native String shkey_print(long jarg1);
  public final static native long ashkey_str(String jarg1);
  public final static native long ashkey_num(int jarg1);
  public final static native int shkey_cmp(long jarg1, long jarg2);
  public final static native long shkey_clone(long jarg1);
  public final static native long shkey_cert(long jarg1, java.math.BigInteger jarg2, long jarg3);
  public final static native int shkey_verify(long jarg1, java.math.BigInteger jarg2, long jarg3, long jarg4);
  public final static native long shkey_gen(String jarg1);
  public final static native long shpool_init();
  public final static native long shpool_size(long jarg1);
  public final static native void shpool_grow(long jarg1);
  public final static native long shpool_get(long jarg1);
  public final static native long shpool_get_index(long jarg1, int jarg2);
  public final static native void shpool_put(long jarg1, long jarg2);
  public final static native void shpool_free(long jarg1);
  public final static native long shmeta_init();
  public final static native void shmeta_free(long jarg1);
  public final static native void shmeta_set(long jarg1, long jarg2, long jarg3);
  public final static native void shmeta_set_str(long jarg1, long jarg2, String jarg3);
  public final static native void shmeta_unset_str(long jarg1, long jarg2);
  public final static native void shmeta_set_void(long jarg1, long jarg2, byte[] jarg3);
  public final static native void shmeta_unset_void(long jarg1, long jarg2);
  public final static native String shmeta_get_str(long jarg1, long jarg2);
  public final static native long shmeta_get_void(long jarg1, long jarg2);
  public final static native long shmeta_get(long jarg1, long jarg2);
  public final static native void shmeta_print(long jarg1, long jarg2);
  public final static native long shmeta_count(long jarg1);
  public final static native void shmeta_unset_ptr(long jarg1, long jarg2);
  public final static native void shmeta_set_ptr(long jarg1, long jarg2, long jarg3);
  public final static native long shmeta_get_ptr(long jarg1, long jarg2);
  public final static native int ashencode(String jarg1, long jarg2, long jarg3);
  public final static native int shencode(String jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native long shencode_str(String jarg1);
  public final static native int ashdecode(long jarg1, long jarg2, long jarg3);
  public final static native int shdecode(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native int shdecode_str(String jarg1, long jarg2);
  public final static native long shlock_open(long jarg1, int jarg2);
  public final static native int shlock_tryopen(long jarg1, int jarg2, long jarg3);
  public final static native int shlock_close(long jarg1);
  public final static native void sh_sha256(long jarg1, long jarg2, long jarg3);
  public final static native String shdigest(long jarg1, int jarg2);
  public final static native String shjson_print(long jarg1);
  public final static native String shjson_str(long jarg1, String jarg2, String jarg3);
  public final static native String shjson_astr(long jarg1, String jarg2, String jarg3);
  public final static native long shjson_str_add(long jarg1, String jarg2, String jarg3);
  public final static native void shjson_free(long jarg1);
  public final static native double shjson_num(long jarg1, String jarg2, double jarg3);
  public final static native long shjson_num_add(long jarg1, String jarg2, double jarg3);
  public final static native long shjson_init(String jarg1);
  public final static native long shjson_array_add(long jarg1, String jarg2);
  public final static native String shjson_array_str(long jarg1, String jarg2, int jarg3);
  public final static native String shjson_array_astr(long jarg1, String jarg2, int jarg3);
  public final static native double shjson_array_num(long jarg1, String jarg2, int jarg3);
  public final static native long shjson_obj(long jarg1, String jarg2);
  public final static native long shjson_strlen(long jarg1, String jarg2);
}
